package com.hyphenate.easeui.model;

import com.hyphenate.easeui.R;
import com.hyphenate.easeui.domain.EaseEmojicon;
import com.hyphenate.easeui.domain.EaseEmojicon.Type;
import com.hyphenate.easeui.utils.EaseSmileUtils;

public class EaseDefaultEmojiconDatas {

    private static String[] emojis = new String[]{
            EaseSmileUtils.ee_1,
            EaseSmileUtils.ee_2,
            EaseSmileUtils.ee_3,
            EaseSmileUtils.ee_4,
            EaseSmileUtils.ee_5,
            EaseSmileUtils.ee_6,
            EaseSmileUtils.ee_7,
            EaseSmileUtils.ee_8,
            EaseSmileUtils.ee_9,
            EaseSmileUtils.ee_10,
            EaseSmileUtils.ee_11,
            EaseSmileUtils.ee_12,
            EaseSmileUtils.ee_13,
            EaseSmileUtils.ee_14,
            EaseSmileUtils.ee_15,
            EaseSmileUtils.ee_16,
            EaseSmileUtils.ee_17,
            EaseSmileUtils.ee_18,
            EaseSmileUtils.ee_19,
            EaseSmileUtils.ee_20,
            EaseSmileUtils.ee_21,
            EaseSmileUtils.ee_22,
            EaseSmileUtils.ee_23,
            EaseSmileUtils.ee_24,
            EaseSmileUtils.ee_25,
            EaseSmileUtils.ee_26,
            EaseSmileUtils.ee_27,
            EaseSmileUtils.ee_28,
            EaseSmileUtils.ee_29,
            EaseSmileUtils.ee_30,
            EaseSmileUtils.ee_31,
            EaseSmileUtils.ee_32,
            EaseSmileUtils.ee_33,
            EaseSmileUtils.ee_34,
            EaseSmileUtils.ee_35,
            EaseSmileUtils.ee_36,
            EaseSmileUtils.ee_37,
            EaseSmileUtils.ee_38,
            EaseSmileUtils.ee_39,
            EaseSmileUtils.ee_40,
            EaseSmileUtils.ee_41,
            EaseSmileUtils.ee_42,
            EaseSmileUtils.ee_43,
            EaseSmileUtils.ee_44,
            EaseSmileUtils.ee_45,
            EaseSmileUtils.ee_46,
            EaseSmileUtils.ee_47,
            EaseSmileUtils.ee_48,
            EaseSmileUtils.ee_49,
            EaseSmileUtils.ee_50,
            EaseSmileUtils.ee_51,
            EaseSmileUtils.ee_52,
            EaseSmileUtils.ee_53,
            EaseSmileUtils.ee_54,
            EaseSmileUtils.ee_55,
            EaseSmileUtils.ee_56,
            EaseSmileUtils.ee_57,
            EaseSmileUtils.ee_58,
            EaseSmileUtils.ee_59,
            EaseSmileUtils.ee_60,
            EaseSmileUtils.ee_61,
            EaseSmileUtils.ee_62,
            EaseSmileUtils.ee_63,
            EaseSmileUtils.ee_64,
            EaseSmileUtils.ee_65,
            EaseSmileUtils.ee_66,
            EaseSmileUtils.ee_67,
            EaseSmileUtils.ee_68,
            EaseSmileUtils.ee_69,
            EaseSmileUtils.ee_70,
            EaseSmileUtils.ee_71,
            EaseSmileUtils.ee_72,
            EaseSmileUtils.ee_73,
            EaseSmileUtils.ee_74,
            EaseSmileUtils.ee_75,
            EaseSmileUtils.ee_76,
            EaseSmileUtils.ee_77,
            EaseSmileUtils.ee_78,
            EaseSmileUtils.ee_79,
            EaseSmileUtils.ee_80,
            EaseSmileUtils.ee_81,
            EaseSmileUtils.ee_82,
            EaseSmileUtils.ee_83,
            EaseSmileUtils.ee_84,
            EaseSmileUtils.ee_85,
            EaseSmileUtils.ee_86,
            EaseSmileUtils.ee_87,
            EaseSmileUtils.ee_88,
            EaseSmileUtils.ee_89,
            EaseSmileUtils.ee_90,
            EaseSmileUtils.ee_91,
            EaseSmileUtils.ee_92,
            EaseSmileUtils.ee_93,
            EaseSmileUtils.ee_94,
            EaseSmileUtils.ee_95,
            EaseSmileUtils.ee_96,
            EaseSmileUtils.ee_97,
            EaseSmileUtils.ee_98,
            EaseSmileUtils.ee_99,
            EaseSmileUtils.ee_100,
//            EaseSmileUtils.ee_101,
//            EaseSmileUtils.ee_102,
//            EaseSmileUtils.ee_103,
//            EaseSmileUtils.ee_104,
//            EaseSmileUtils.ee_105,
    };

    private static int[] icons = new int[]{
            R.drawable.expression_1,
            R.drawable.expression_2,
            R.drawable.expression_3,
            R.drawable.expression_4,
            R.drawable.expression_5,
            R.drawable.expression_6,
            R.drawable.expression_7,
            R.drawable.expression_8,
            R.drawable.expression_9,
            R.drawable.expression_10,
            R.drawable.expression_11,
            R.drawable.expression_12,
            R.drawable.expression_13,
            R.drawable.expression_14,
            R.drawable.expression_15,
            R.drawable.expression_16,
            R.drawable.expression_17,
            R.drawable.expression_18,
            R.drawable.expression_19,
            R.drawable.expression_20,
            R.drawable.expression_21,
            R.drawable.expression_22,
            R.drawable.expression_23,
            R.drawable.expression_24,
            R.drawable.expression_25,
            R.drawable.expression_26,
            R.drawable.expression_27,
            R.drawable.expression_28,
            R.drawable.expression_29,
            R.drawable.expression_30,
            R.drawable.expression_31,
            R.drawable.expression_32,
            R.drawable.expression_33,
            R.drawable.expression_34,
            R.drawable.expression_35,
            R.drawable.expression_36,
            R.drawable.expression_37,
            R.drawable.expression_38,
            R.drawable.expression_39,
            R.drawable.expression_40,
            R.drawable.expression_41,
            R.drawable.expression_42,
            R.drawable.expression_43,
            R.drawable.expression_44,
            R.drawable.expression_45,
            R.drawable.expression_46,
            R.drawable.expression_47,
            R.drawable.expression_48,
            R.drawable.expression_49,
            R.drawable.expression_50,
            R.drawable.expression_51,
            R.drawable.expression_52,
            R.drawable.expression_53,
            R.drawable.expression_54,
            R.drawable.expression_55,
            R.drawable.expression_56,
            R.drawable.expression_57,
            R.drawable.expression_58,
            R.drawable.expression_59,
            R.drawable.expression_60,
            R.drawable.expression_61,
            R.drawable.expression_62,
            R.drawable.expression_63,
            R.drawable.expression_64,
            R.drawable.expression_65,
            R.drawable.expression_66,
            R.drawable.expression_67,
            R.drawable.expression_68,
            R.drawable.expression_69,
            R.drawable.expression_70,
            R.drawable.expression_71,
            R.drawable.expression_72,
            R.drawable.expression_73,
            R.drawable.expression_74,
            R.drawable.expression_75,
            R.drawable.expression_76,
            R.drawable.expression_77,
            R.drawable.expression_78,
            R.drawable.expression_79,
            R.drawable.expression_80,
            R.drawable.expression_81,
            R.drawable.expression_82,
            R.drawable.expression_83,
            R.drawable.expression_84,
            R.drawable.expression_85,
            R.drawable.expression_86,
            R.drawable.expression_87,
            R.drawable.expression_88,
            R.drawable.expression_89,
            R.drawable.expression_90,
            R.drawable.expression_91,
            R.drawable.expression_92,
            R.drawable.expression_93,
            R.drawable.expression_94,
            R.drawable.expression_95,
            R.drawable.expression_96,
            R.drawable.expression_97,
            R.drawable.expression_98,
            R.drawable.expression_99,
            R.drawable.expression_100,
//            R.drawable.expression_101,
//            R.drawable.expression_102,
//            R.drawable.expression_103,
//            R.drawable.expression_104,
//            R.drawable.expression_105
    };


    private static final EaseEmojicon[] DATA = createData();

    private static EaseEmojicon[] createData() {
        EaseEmojicon[] datas = new EaseEmojicon[icons.length];
        for (int i = 0; i < icons.length; i++) {
            datas[i] = new EaseEmojicon(icons[i], emojis[i], Type.NORMAL);
        }
        return datas;
    }

    public static EaseEmojicon[] getData() {
        return DATA;
    }
}
